### ISSUE TITLE
Data Generator throws exception from IotHub

### ISSUE THREAD

**Issue by markjbrown** [solliancenet/cosmos-db-scenario-based-labs#8]
After running the data generator for 15 minutes I encountered this error. Exception, stack trace and screen cap below.

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. ('sender169' is closed) ('sender266' is closed)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(CancellationToken cancellationToken)
   at FleetDataGenerator.Program.<Main>d__13.MoveNext() in C:\cosmos-db-scenario-based-labs-master\IoT\Starter\FleetDataGenerator\Program.cs:line 189

Inner Exception 1:
AmqpException: 'sender169' is closed

Here is stack trace on one of the exceptions.

"   at Microsoft.Azure.Amqp.AmqpObject.ThrowIfClosed()\r\n   at Microsoft.Azure.Amqp.SendingAmqpLink.BeginSendMessage(AmqpMessage message, ArraySegment`1 deliveryTag, ArraySegment`1 txnId, TimeSpan timeout, AsyncCallback callback, Object state)\r\n   at Microsoft.Azure.Amqp.SendingAmqpLink.<>c__DisplayClass11_0.<SendMessageAsync>b__0(AsyncCallback c, Object s)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)\r\n   at Microsoft.Azure.Amqp.SendingAmqpLink.SendMessageAsync(AmqpMessage message, ArraySegment`1 deliveryTag, ArraySegment`1 txnId, TimeSpan timeout)\r\n   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSendingLink.<SendAmqpMessageAsync>d__10.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSendingLink.<SendMessageAsync>d__8.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.<SendMessageAsync>d__31.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.<SendEventAsync>d__36.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.<SendEventAsync>d__11.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__23`1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<SendEventAsync>d__14.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at FleetDataGenerator.SimulatedVehicle.<SendEvent>d__33.MoveNext() in C:\\cosmos-db-scenario-based-labs-master\\IoT\\Starter\\FleetDataGenerator\\SimulatedVehicle.cs:line 136\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at FleetDataGenerator.SimulatedVehicle.<SendDataToHub>d__32.MoveNext() in C:\\cosmos-db-scenario-based-labs-master\\IoT\\Starter\\FleetDataGenerator\\SimulatedVehicle.cs:line 109\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at FleetDataGenerator.SimulatedVehicle.<RunVehicleSimulationAsync>d__30.MoveNext() in C:\\cosmos-db-scenario-based-labs-master\\IoT\\Starter\\FleetDataGenerator\\SimulatedVehicle.cs:line 65"

 
![image](https://user-images.githubusercontent.com/800166/66255796-e8205d80-e73c-11e9-9dbb-479fd5570853.png)

**Comment by joelhulen** [comment]
I cannot reproduce this error. Have you encountered it again?
